insert into public.framework_definitions
  (framework_key, stage_key, stage_order, name_es, name_en, strategic_purpose_es, strategic_purpose_en)
values
  ('wave10', 'welcome', 1, 'Bienvenida', 'Welcome',
   'Abre el webinar, fija expectativas (duración, qué se van a llevar) y establece la credibilidad del presentador antes de pedir ninguna atención sostenida.',
   'Opens the webinar, sets expectations (length, what they will walk away with), and establishes the presenter''s credibility before asking for any sustained attention.'),
  ('wave10', 'align', 2, 'Alineación', 'Align',
   'Nombra el objetivo o la situación que trajo a la audiencia hasta acá, para que sientan que este webinar es exactamente para ellos desde el minuto uno.',
   'Names the goal or situation that brought the audience here, so they feel this webinar is exactly for them from minute one.'),
  ('wave10', 'validate', 3, 'Validación', 'Validate',
   'Confirma que el problema es real, es común y vale la pena resolverlo ahora -- sin esto, todo lo que sigue se siente como una solución buscando un problema.',
   'Confirms the problem is real, common, and worth solving now -- without this, everything that follows feels like a solution looking for a problem.'),
  ('wave10', 'engage', 4, 'Enganche', 'Engage',
   'Ancla la atención con una promesa concreta o una historia que la audiencia pueda seguir de principio a fin, antes de entrar en contenido educativo.',
   'Anchors attention with a concrete promise or a story the audience can follow start to finish, before moving into educational content.'),
  ('wave10', 'reframe', 5, 'Replanteo', 'Reframe',
   'Introduce el mecanismo único o el cambio de paradigma que explica por qué los intentos anteriores de la audiencia no funcionaron.',
   'Introduces the unique mechanism or paradigm shift that explains why the audience''s previous attempts did not work.'),
  ('wave10', 'evidence', 6, 'Evidencia', 'Evidence',
   'Respalda el mecanismo con datos, casos o demostraciones concretas -- la etapa que convierte una afirmación en algo creíble.',
   'Backs the mechanism with data, case studies, or concrete demonstrations -- the stage that turns a claim into something believable.'),
  ('wave10', 'bridge', 7, 'Puente', 'Bridge',
   'Conecta la evidencia con la oferta específica, para que la transición a "esto es lo que te ofrezco" se sienta como el paso lógico siguiente.',
   'Connects the evidence to the specific offer, so the transition to "here is what I''m offering" feels like the obvious next step.'),
  ('wave10', 'derisk', 8, 'Reducción de riesgo', 'De-risk',
   'Atiende las objeciones más probables y reduce el riesgo percibido de actuar (garantía, soporte, casos similares) antes de pedir la decisión.',
   'Addresses the most likely objections and lowers the perceived risk of acting (guarantee, support, similar cases) before asking for the decision.'),
  ('wave10', 'activate', 9, 'Activación', 'Activate',
   'Presenta la oferta y el llamado a la acción de forma clara y sin ambigüedad -- una sola acción primaria, nunca varias compitiendo entre sí.',
   'Presents the offer and the call to action clearly and unambiguously -- one primary action, never several competing with each other.'),
  ('wave10', 'learn', 10, 'Aprendizaje', 'Learn',
   'Cierra con preguntas y respuestas y deja capturada la señal (objeciones reales, preguntas repetidas) que retroalimenta la siguiente iteración de la presentación.',
   'Closes with Q&A and captures the signal (real objections, repeated questions) that feeds back into the next iteration of the presentation.')
on conflict (framework_key, stage_key) do nothing;
